-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 10, 2016 at 12:09 PM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 7.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `johnmae_thesis`
--

-- --------------------------------------------------------

--
-- Table structure for table `comment_section_post`
--

CREATE TABLE `comment_section_post` (
  `NO` int(11) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `COMMENTHERE` varchar(500) NOT NULL,
  `DATECOMMENT` varchar(50) NOT NULL,
  `POSTNO` varchar(200) NOT NULL,
  `TEMPLATENAME` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `comment_section_post`
--

INSERT INTO `comment_section_post` (`NO`, `NAME`, `EMAIL`, `COMMENTHERE`, `DATECOMMENT`, `POSTNO`, `TEMPLATENAME`) VALUES
(12, 'Jm Abril', 'johnmark_abri12l@yahoo.com', 'Hello! This is John Mark. Nice post :)', 'October 1, 2016 04:45 AM', '3', 'DESIGN2'),
(13, 'Jm Abril', 'johnmark_abri12l@yahoo.com', 'First Comment', 'October 3, 2016 11:58 AM', '1', 'DESIGN2'),
(14, 'Jm Abril', 'johnmark_abri12l@yahoo.com', 'Second Comment', 'October 3, 2016 11:59 AM', '1', 'DESIGN2'),
(15, 'Jm Abril', 'johnmark_abri12l@yahoo.com', '(DOWNLOAD(y)), (COMMENT BOX), (VIDEO)- walang internet, yung lang HAPPY BIRHTDAY !!', 'October 5, 2016 3:24 AM', '2', 'DESIGN2'),
(16, 'Jm Abril', 'johnmark_abri12l@yahoo.com', 'Si Farrah ay maliit.', 'October 5, 2016 3:29 PM', '2', 'DESIGN2'),
(17, 'Jm Abril', 'johnmark_abri12l@yahoo.com', 'sjfdfsdafsdaasdfafsd', 'October 6, 2016 3:47 PM', '2', 'DESIGN2'),
(18, 'Jm Abril', 'johnmark_abri12l@yahoo.com', 'kjasdhfkjhaskdhsad', 'October 6, 2016 5:28 PM', '1', 'DESIGN2');

-- --------------------------------------------------------

--
-- Table structure for table `posted`
--

CREATE TABLE `posted` (
  `NO` int(11) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `ACCOUNT_TYPE` varchar(20) NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `IMAGEURL` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(5000) NOT NULL,
  `DATE` varchar(50) NOT NULL,
  `TEMPLATENAME` varchar(50) NOT NULL,
  `RECIPES` varchar(5000) NOT NULL,
  `COMMAND` varchar(50) NOT NULL,
  `PRICE` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `posted`
--

INSERT INTO `posted` (`NO`, `NAME`, `ACCOUNT_TYPE`, `TITLE`, `IMAGEURL`, `DESCRIPTION`, `DATE`, `TEMPLATENAME`, `RECIPES`, `COMMAND`, `PRICE`) VALUES
(1, 'Jm Abril', 'User', 'Heart Cupcakes', 'post-1.jpg', 'These heart-in-the-middle cupcakes are so cute and are easy to make! Change the center shape for lots of different holidays and celebrations.', 'September 17, 2016 06:45 PM', 'DESIGN2', '1 Box|Cake Mix|3 Pieces|Large Eggs|1/2 Cup|Melted Butter(not margarine)|1 Cup|Water', 'FREE', ''),
(2, 'Mae Gregorio', 'Administrator', 'Pink Lemon Cupcakes', 'post-2.jpg', 'Today''s post comes to you compliments of the fact that I can''t actually raise my arms higher than the keyboard. Last week has been a whirlwind of activity including work, showing an out-of-town guest around the city, more work, running after my amazing sister as she did the Chicago Triathlon (to take pictures, of course, no way am I doing THAT anytime soon), and helping move a friend''s parents halfway across town. It is not an understatement when I say that everything hurts. For example, did you know that the muscles in your fingers could be sore? I surely didn''t. Somewhere in that insanity I had also found time to make two dozen lemon cupcakes for a bridal shower for a friend at work.|I hadn''t actually had time to go grocery shopping in weeks, so the fact that these cupcakes came out with all my substitutions and tweaks is actually a bit of a miracle, but they came out great, tender and just the right combination of tart and sweet, and were devoured by my coworkers in just a few minutes. ', 'September 22, 2016  02:16 PM', 'DESIGN2', '2 1/4 cups|flour|1 Tbsp|baking powder|1/2 tsp|salt|1 cup|milk (I used 1%)lemon zest from two lemons|1/4 cup|lemon juice, from the two lemons you zested|4 pieces|large egg whites|1 1/2 cups|sugar|8 Tbsps|(1 stick) unsalted butter, at room temp|1 tsp|vanilla extract\n1/2 teaspoon lemon extract (or lemon oil if you have it)', 'FREE', ''),
(3, 'Mae Gregorio', 'Administrator', 'Vegan Vanilla Cupcake Recipe', 'post-3.jpg', 'I also think that these would make a perfect Valentines Day gift! Decorate with cute little vegan heart-shaped lollies for a romantic edible gift!|Ok... when I first undertook a vegan lifestyle I asked myself, "Will I ever be able to eat another cupcake?". I shuddered at the thought so I developed this FAIL-PROOF cupcake recipe. I had published this on Veggieful a few months ago but I decided to revamp the page and change the frosting recipes. So, lets cut to the chase... these are most delicious and the fluffiest vegan cupcakes I have EVER eaten! I am not joking. I made a massive batch of these the other day for recipe-testing purposes. One half went to Jerome''s work and the other half went to our friends and family. There were many compliments and amazed responses to these easy cupcakes... my mum said that they were the "best cupcakes" she had "ever eaten" while Jerome''s co-worker stated that they were the "fluffiest" cupcakes she had ever had... little did she know that they were vegan! Tee hee hee. I find that when I make these for others, there are a number of things guaranteed... Firstly, you will be asked for the recipe. Secondly, they will devour it in seconds and lastly, they will be talking about them for days. As I said above, these are a fail-proof recipe... meaning, I have never had a problem with them, they always work out and they never fail to impress others. Every person needs an amazing cupcake recipe... and this is it! Check out our frosting and icing recipes.', 'September 22, 2016  02:16 PM', 'DESIGN2', '1 cup|all-purpose flour, sifted|2 teaspoons|baking powder|pinch|salt|½ cup|vegan white sugar|1/4 cup|plain-flavoured oil|¾ cup|Soy Milky Lite|1 teaspoon|vanilla extract|½ tablespoon|apple cider vinegar', 'FREE', ''),
(4, 'Mae Gregorio', 'Administrator', 'Icee Cupcakes', 'r1.jpg', 'Softball season is officially over. It’s kind of sad, really, because Jordan loved it so much. I will not miss having to get dinner ready for her at 4:00 and packing it up in a cooler for Mel and I. Nor will I miss the post-school night-game whining.\r\n|\r\nI will miss watching Jordan learn how to catch. And watching her hit, without a tee, for entire games.\r\n|\r\nLast weekend I volunteered to host the end-of-the-year softball party. For 12 first-graders, their parents, and siblings.\r\n|\r\nYes, I’m certifiably insane.\r\n|\r\nBut I love doing it. Even when I was going crazy on Friday trying to get the house clean and do last minute prep and make eight dozen mini cupcakes, when I was growling “why do I do this???” at my husband, I still was having fun.\r\n|\r\nFor the cupcakes, I decided to go with a “softball snack shack” theme. You know, that crap you buy while you’re bored out of your mind watching your kid play. Popcorn, hot cocoa, Icees, candy.\r\n|\r\nI made mini cupcakes out of two box mixes, one yellow cake and one chocolate. FYI, that makes a lot of minis. I had no idea how many it would make. Be prepared. Probably 3-4 dozen per box.\r\n|\r\n{Just because I majored in math, you didn’t expect me just know that a mix making 24 regular sized cupcakes would make a whole lot of mini ones, right?}\r\n|\r\nI made one large batch of homemade buttercream and divided it into four portions to make the four flavors of cupcake.\r\n|\r\nThese ICEE cupcakes were the biggest hit. The frosting is made with cherry jell-o. Joan at Chocolate, Chocolate, and More used Jell-O in cupcakes awhile back and when brainstorming ideas, I came up with these.\r\n|\r\nThe straws are from Target. I may have * accidentally* brought home a couple extra with my diet Pepsi fountain drink. Cut them in fourths and they are the perfect size for mini cupcakes.\r\n|\r\nHere is a link to the printable ICEE logo. I printed them on regular paper and attached them to a paper liner with double stick tape. Using those cute little paper cups would be great too, but I didn’t have any.\r\n|\r\nI must say, if you’re making cupcakes for a crowd, make minis. People eat more when food is miniature. I had no cupcakes left. The kids ate way too many, but hey, then I didn’t.', 'September 28, 2016 11:12 PM', 'DESIGN2', '1 box |yellow cake mix made and baked as directed in mini cupcake pans (about 4 dozen cupcakes)|\r\n1 cup| room temperature butter|\r\n4 cups| powdered sugar|\r\n1 teaspoon |vanilla|\r\n1 small box| cherry Jell-O mix|\r\n1-2 tablespoons| maraschino cherry juice (optional)|\r\n1 piece|Cream or milk if needed for consistency|\r\n1 piece|Red straws', 'SELL', '350.00'),
(5, 'Mae Gregorio', 'Administrator', 'Strawberry Filled Cupcakes', 'r2.jpg', 'I love to find unique and fun cupcake recipes to try and thought these Strawberry Filled Cupcakes with Cream Cheese Frosting might be good. They turned out to be AMAZING! They are really easy to make, but look and taste like something straight out of a gourmet bakery.  |\r\nDefinitely a must-try recipe!', 'October 06, 2016 04:07 AM', 'DESIGN2', 'Boxed |cake mix (I use this kind)|\r\n3 pieces| Large Eggs|\r\n1/2 cup |melted butter (not margarine)|\r\n1 cup| water|\r\n\r\nOne jar| high-end strawberry jelly or preserves (my favorite)|\r\n2 oz |Cream Cheese|\r\n1/4 cup |powdered sugar|\r\n\r\n10 Tbsp |butter, slightly firm but not cold|\r\n10 oz |cream cheese, cold|\r\n2 1 /2 Tbsp |sour cream|\r\n1/2 tsp |vanilla extract|\r\n5 cups |powdered sugar|', 'SELL', '300.00'),
(6, 'Mae Gregorio', 'Administrator', 'Apple Cupcakes', 'post-9.jpg', 'In-season Red Delicious apples are the inspiration for these adorable fall treats.', 'October 09, 2016 02:05 PM', 'DESIGN2', '1 piece|Cupcakes (homemade or storebought) with red cupcake liners|\r\n1 piece|Unfrosted mini doughnuts|\r\n1 piece|Red-tinted buttercream frosting|\r\n1 piece|Red sanding sugar|\r\n1 piece|Pretzel sticks|\r\n1 piece|Green sour strap candy', 'FREE', ''),
(7, 'Mae Gregorio', 'Administrator', 'S’MORE CUPCAKES', 'post-10.jpg', 'There''s no getting around the fact that these cupcakes take a little leg work, but one bite will prove they''re worth it, with a graham cracker and chocolate crust layered with a chocolate cake and finished with fluffy marshmallow topping.', 'October 09, 2016 02:17 PM', 'DESIGN2', '6 pieces | graham cracker boards (oblongs)	|\n2 tbsp.  | each sugar and melted butter	|\n½ 		 | c. mini semisweet chocolate chips	|\n2¼ | c. all-purpose flour |\n1½ | c. sugar |\n¾ | c. unsweetened cocoa powder |\n¾ tsp. | baking soda |\n¼ tsp.|  salt |\n1¼  | c. buttermilk |\n2 piece  | large eggs |\n½  | c. each canola oil and water |\n1 tbsp. |  Tbsp vanilla extract |\n6 pieces |large egg whites|\n1½| c. sugar|\n½ tsp. |cream of tartar|\n1 tsp.| vanilla extract|\n1 piece|Small handheld butane torch\n', 'FREE', ''),
(8, 'Mae Gregorio', 'Administrator', 'LEMON-HONEY CUPCAKES', '', 'Guests will be buzzing about these fluffy cupcakes, which have grated lemon zest, lemon juice and honey not only in the batter, but in the luscious frosting as well. Add a little sparkle by finishing them with a sprinkling of sanding sugar or a candy bee.', 'October 10, 2016 04:20 PM', 'DESIGN2', '2¾ c.| all-purpose flour|\r\n¾ tsp.| each baking powder and baking soda|\r\n½ tsp.| salt|\r\n½ c.| reduced-fat sour cream|\r\n¼ c.| milk|\r\n1½ tbsp.| grated lemon zest|\r\n4 tbsp.| lemon juice|\r\n¾ c.| unsalted butter|\r\n¾ c.| honey|\r\n¼ c.| sugar|\r\n3| large eggs|\r\n1 c.| unsalted butter|\r\n¼ c.| honey|\r\n1½ tbsp.| grated lemon zest|\r\n4 c.| confectioners’ sugar|\r\n7 tsp. to 8 tsp| lemon juice|\r\nFew drops| yellow food color|\r\n1pc| Tootsie Roll|\r\n2 piece| of string|\r\n1pc| Yellow peanut M&M|\r\n1pc| Brown food marker|\r\n1pc| Clear spice drop candies|\r\n1pc| Small cookie cutter|\r\n', 'FREE', ''),
(9, 'Mae Gregorio', 'Administrator', 'CHOCOLATE LOVEBUGS', '', 'These adorable cupcakes are sure to warm your sweetie''s heart and stomach! ', 'October 10, 2016 4:25 PM', 'DESIGN2', 'Mini| paper liners|\r\n? c.| granulated sugar|\r\n½ c.| all-purpose flour|\r\n3 tbsp.| unsweetened dark cocoa|\r\n1 tsp.| baking powder|\r\n¼ tsp.| kosher salt|\r\n4| large egg whites|\r\n2 tbsp.| canola oil|\r\n1 tsp.| pure vanilla extract|\r\n2 oz.| bittersweet chocolate|\r\n3| large egg whites|\r\n½ tsp.| cream of tartar|\r\n1 lb.| confectioners'' sugar|\r\nRed gel| food coloring|\r\nRed, pink, and white| medium nonpareils|\r\nRed, pink, and white| sugar hearts|\r\n1pc| Sanding sugar|\r\n', 'FREE', ''),
(10, 'Mae Gregorio', 'Administrator', 'STRAWBERRY SHORT-CUPCAKES', '', 'Transform this classic treat with a homemade cupcake that''s filled with an irresistible combination of whipped cream, strawberry jam, orange zest and strawberries.', 'October 10, 2016 04:30 PM', 'DESIGN2', '1pc| Baking spray (cooking spray with flour)|\r\n2 stick| butter|\r\n1½ c.| granulated sugar|\r\n1 tbsp.| baking powder|\r\n½ tsp.| salt|\r\n4| large eggs|\r\n1 c.| milk|\r\n2 tsp.| vanilla extract|\r\n2.67 c. all-purpose flour\r\n½ c.| seedless strawberry jam|\r\n1 tsp.| grated orange zest|\r\n2 tsp.| freshly squeezed orange juice|\r\n1 container| strawberries|\r\n1¾ c.| heavy (whipping) cream|\r\n3 tbsp.| confectioners’ sugar|\r\nGarnish:| additional strawberries, quartered (optional)| \r\n', 'FREE', ''),
(11, 'Mae Gregorio', 'Administrator', 'PEANUT BUTTER AND CHOCOLATE CUPCAKES', '', 'The ultimate recipe for PB-and-chocolate fans, these moist, chocolatey cupcakes come complete with a sweet peanut butter filling and a silky slathering of chocolate–sour cream frosting. ', 'October 10, 2016 04:33 PM', 'DESIGN2', '1¾ c.| all-purpose flour|\r\n½ c.| unsweetened cocoa powder|\r\n1 tsp.| baking soda|\r\n½ tsp.| salt|\r\n½ c.| milk|\r\n½ c.| reduced-fat sour cream|\r\n¾ c.| unsalted butter|\r\n1¼ c.| sugar|\r\n½ c.| creamy peanut butter|\r\n3| large eggs|\r\n½ c.| creamy peanut butter|\r\n3 tbsp.| unsalted butter|\r\n1½ c.| confectioners’ sugar|\r\n3 to 4 Tbsp| milk|\r\n2 c.| semisweet chocolate chips|\r\n1 c.| reduced-fat sour cream|\r\n', 'FREE', ''),
(12, 'Mae Gregorio', 'Administrator', 'COCONUT CUPCAKES AND COCONUT-WHITE CHOCOLATE FROSTING', '', 'The great thing about coconut is its versatility; it feels refreshing in warm weather and comforting in cold. This recipe makes the most of it, featuring a triple whammy of coconut in the batter—flakes, extract and milk—and a coconut cream cheese frosting.', 'October 10, 2016 04:35 PM', 'DESIGN2', '2¼ c.| all-purpose flour|\r\n2 tsp.| baking powder|\r\n½ tsp.| salt|\r\n½ c.| sweetened flaked coconut|\r\n¾ c.| unsalted butter|\r\n1½ c.| sugar|\r\n3| large eggs|\r\n½ tsp.| coconut extract or vanilla extract|\r\n¾ c. light coconut milk (not cream of coconut)\r\n1 c.| white chocolate baking chips|\r\n½ c.| unsalted butter|\r\n1 brick| cream cheese|\r\n½ tsp.| coconut extract|\r\n2½ c.| confectioners’ sugar|\r\nGarnish:| sweetened flaked coconut, toasted|\r\n', 'FREE', ''),
(13, 'Mae Gregorio', 'Administrator', 'BOSTON CREAM CUPCAKES', '', 'This miniature version of the classic custard pie leaves nothing out, with rich vanilla pudding, buttermilk and a semisweet chocolate glaze. ', 'October 10, 2016 04:36 PM', 'DESIGN2', '2½ c.| all-purpose flour|\r\n¾ tsp.| baking soda|\r\n½ tsp.| each baking powder and salt|\r\n¾ c.| unsalted butter|\r\n1¼ c.| sugar|\r\n3| large eggs|\r\n2 tsp.| vanilla extract|\r\n1 c.| buttermilk|\r\n1 package| cook & serve vanilla pudding|\r\n1¼ c.| milk|\r\n½ tsp.| vanilla extract|\r\n8 oz.| chopped|\r\n? c.| each sugar and water|\r\n3 tbsp.| unsalted butter|\r\n', 'FREE', ''),
(14, 'Mae Gregorio', 'Administrator', 'LEMON BUTTERFLY CAKES', '', 'Famed for her cake pops, Bakerella (a.k.a. Angie Dudley) whipped up these cheery cupcakes as a special treat for Woman''s Day. They''re full of lemony flavor and only require simple baking and kitchen tools.', 'October 10, 2016 04:37 PM', 'DESIGN2', '1¼ c.| all-purpose flour|\r\n1 tsp.| baking powder|\r\n½ tsp.| kosher salt|\r\n1 c.| granulated sugar|\r\n1¼ c.| unsalted butter|\r\n2| large eggs|\r\n1 tbsp.| lemon zest|\r\n1 tsp.| pure vanilla extract|\r\n2 tbsp.| fresh lemon juice|\r\n¼ c.| whole milk|\r\n3 c.| confectioners’ sugar|\r\n1pc| white sanding sugar|\r\n12| Good & Fruity or Good & Plenty candies or jelly beans|\r\n1pc| Candy Butterfly Wings| \r\n', 'FREE', ''),
(15, 'Mae Gregorio', 'Administrator', 'GRASSY LEMON CUPCAKES WITH BEES AND FLOWERS', '', 'These cupcakes will have your guests buzzing!', 'October 10, 2016 04:38 PM', 'DESIGN2', '2 1/2 c.| all-purpose flour|\r\n2 tsp.| baking powder|\r\n1/2 tsp.| kosher salt|\r\n1 1/2 c.| granulated sugar|\r\n1 tbsp.| fresh lemon zest|\r\n2 tbsp.| fresh lemon juice|\r\n1 tsp.| pure vanilla extract|\r\n1 c. (2 sticks)| unsalted butter, at room temperature|\r\n3| large eggs|\r\n1 c.| whole milk|\r\n1 c. (2 sticks)| unsalted butter, at room temperature|\r\n1 lb.| confectioners sugar|\r\n2 tbsp.| heavy cream|\r\n2 tsp.| pure vanilla extract|\r\n1pc| green gel paste food coloring|\r\n1pc| Yellow fondant|\r\n1pc| Black fondant|\r\n1pc| Corn syrup|\r\n1pc| Sliced almonds|\r\n1pc| Flower stamens|\r\n1pc| Royal icing| \r\n', 'FREE', ''),
(16, 'Mae Gregorio', 'Administrator', 'CARROT CUPCAKES WITH HONEY CREAM CHEESE', '', 'PER CUPCAKE 377 CAL, 21 G FAT (5 G SAT FAT), 54 MG CHOL, 290 MG SOD, 5 G PRO, 44 G CAR, 1 G FIBER', 'October 10, 2016 04:40 PM', 'DESIGN2', '1pc| Parchment paper|\r\n1/2 c.| walnuts|\r\n1 1/2 c.| all-purpose flour|\r\n1 tsp.| baking powder|\r\n1 tsp.| baking soda|\r\n2 tsp.| pumpkin pie spice|\r\n1/4 tsp.| kosher salt|\r\n1/2 c.| dark brown sugar|\r\n1/4 c.| granulated sugar|\r\n2| large eggs|\r\n1/2 c.| canola oil|\r\n2 tbsp.| fresh orange juice|\r\n1/2 lb.| carrots, peeled and grated (about 1 3/4 cups)|\r\n1/2 c.| golden raisins|\r\n1/4 c.| dried apricots, roughly chopped|\r\n1 8-ounce| package cream cheese, at room temperature|\r\n1/3 c.| sour cream|\r\n1/2 c.| confectioners'' sugar|\r\n2 tbsp.| honey|\r\n1pc |Orange and green gel paste food colors, for decorating| \r\n', 'FREE', ''),
(17, 'Mae Gregorio', 'Administrator', 'MORPHOS BUTTERFLIES CUPCAKES', '', 'These cupcakes may look too good to eat, but we assure you they''ll fly off of the table. The candy details are just as delicious as the cupcakes themselves.', 'October 10, 2016 04:42 PM', 'DESIGN2', '1½ c.| dark cocoa melting wafers|\r\n1½ c.| blue candy melting wafers|\r\n2 tbsp.| yellow nonpareils|\r\n¾ c.| dark chocolate frosting|\r\n1½ c.| Vanilla Frosting|\r\n12| vanilla cupcakes baked in white paper liners|\r\n¾ c.| white coarse decorating sugar|\r\n24| brown M&M''s|\r\n', 'FREE', ''),
(18, 'Mae Gregorio', 'Administrator', 'ROSE PETAL CUPCAKES', '', 'The only thing better than fresh roses are roses you can eat—or at least the petals! Frosting aficionados, this is the recipe for you.', 'October 10, 2016 04:43 PM', 'DESIGN2', '1 box| French vanilla cake mix|\r\n1½ c.| light unsweetened coconut milk|\r\n3| large eggs|\r\n¼ c.| canola oil|\r\n1½ tsp.| each coconut and vanilla extract|\r\n', 'FREE', ''),
(19, 'Mae Gregorio', 'Administrator', 'ICE CREAM', '', 'These mini takes on ice cream cake are loaded with possibilities. Once the milk chocolate shell sets, you can fill it with any flavor of frozen confection. Then just add a dollop of whipped topping and decorate with a cute cookie for a single-serving summer treat.', 'October 10, 2016 04:44 PM', 'DESIGN2', '½ c.| milk-chocolate chips|\r\n1 pt.| Ice cream|\r\n.67 c.| Frozen Whipped Topping|\r\n1pc| Liquid food colors (optional)|\r\nGarnish:| 4 Keebler Bug Bites cinnamon graham crackers, decorated (directions follow)|\r\n', 'FREE', ''),
(20, 'Mae Gregorio', 'Administrator', 'HIDDEN SURPRISE CUPCAKES', '', 'Strawberry fans take note: This luscious cupcake recipe is for you, with a fluffy white cake filled with a sweet strawberry jam center and a thick cream cheese frosting flecked with fresh berries.', 'October 10, 2016 04:45 PM', 'DESIGN2', '1 stick| unsalted butter|\r\n.67 c.| sugar|\r\n1½ tsp.| baking powder|\r\n¼ tsp.| salt|\r\n2| large eggs|\r\n½ c.| milk|\r\n1 tsp.| vanilla extract|\r\n1½ c.| all-purpose flour|\r\n½ c.| seedless strawberry jam|\r\n½ c.| diced strawberries|\r\n3 tbsp.| sugar|\r\n3 oz.| chilled cream cheese|\r\n¾ c.| heavy (whipping) cream|\r\nGarnish:| 12 whole strawberries| \r\n', 'FREE', ''),
(21, 'Mae Gregorio', 'Administrator', 'BROWNIE CUPCAKES', '', 'This recipe jazzes up your basic brownie with a decadent cream cheese topping, fresh raspberries and a fun new shape.', 'October 10, 2016 04:46 PM', 'DESIGN2', '4 oz.| cream cheese|\r\n½ stick| butter|\r\n2 c.| confectioners’ sugar|\r\n1 stick| butter|\r\n4 oz.| SemiSweet Baking Chocolate|\r\n1 c.| sugar|\r\n2 tsp.| vanilla extract|\r\n3| large eggs|\r\n2/3 c.| all-purpose flour|\r\n2 tbsp.| unsweetened cocoa powder|\r\n½ tsp.| baking powder|\r\nGarnish:| 12 fresh raspberries| \r\n', 'FREE', ''),
(22, 'Mae Gregorio', 'Administrator', '“CORN-ON-THE-COBCAKES” WITH BROWN BUTTER CREAM FROSTING', '', 'If you''re not a jelly bean enthusiast, don''t be deterred—these cupcakes are every bit as delightful without them, featuring a unique cornmeal batter and heavenly brown butter frosting.', 'October 10, 2016 04:28 47', 'DESIGN2', '2| large eggs|\r\n¾ c.| canola oil|\r\n1¼ c. plus 5 Tbsp| whole milk|\r\n3 tsp.| pure vanilla extract|\r\n2½ c.| all-purpose flour|\r\n1½ c.| granulated sugar|\r\n½ c.| yellow cornmeal|\r\n2 tsp.| baking powder|\r\n½ tsp.| plus pinch kosher salt|\r\n¾ c.| unsalted butter|\r\n1 box| confectioners’ sugar|\r\n16| corn holders, assorted yellow and white jelly beans, 4 yellow fruit chews (such as Starburst), black and white sanding sugar|\r\n', 'FREE', ''),
(23, 'Mae Gregorio', 'Administrator', 'SPECIAL MOCHA CUPCAKES', '', '"Topped with a fluffy frosting and chocolate sprinkles, these extra rich, extra delicious cupcakes smell wonderful while baking — and taste even better!"', 'October 10, 2016 04:48 PM', 'DESIGN2', '1 1?2 cups| flour|\r\n1 cup| sugar|\r\n1?3 cup| baking cocoa|\r\n1 teaspoon| baking soda|\r\n1?2 teaspoon| salt|\r\n2| eggs|\r\n1?2 cup| cold brewed coffee|\r\n1?2 cup| vegetable oil|\r\n3 teaspoons| cider vinegar|\r\n3 teaspoons| vanilla extract|\r\n3 tablespoons| semi-sweet chocolate chips|\r\n3 tablespoons| milk chocolate chips|\r\n1?3 cup| butter, softened|\r\n2 cups| confectioners'' sugar|\r\n1 -2 tablespoon| brewed coffee|\r\n1?2 cup| chocolate sprinkles| \r\n', 'FREE', ''),
(24, 'Mae Gregorio', 'Administrator', 'RAINBOW BRIGHT CUPCAKES', '', 'Kids and adults alike will love these festive rainbow cupcakes! Their secret ingredient (sour cream — shhh!) makes them extra rich.', 'October 10, 2016 04:49 PM', 'DESIGN2', '1 (18 ounce) box| yellow cake mix|\r\n4| eggs|\r\n1?2 cup| vegetable oil|\r\n1?2 cup| water|\r\n8 ounces| sour cream|\r\n1 small| vanilla instant pudding mix|\r\n1pc| food coloring (Red, Blue, Yellow, Green and Purple)|\r\n1pc| vanilla or cream cheese frosting, of choice| \r\n', 'FREE', ''),
(25, 'Mae Gregorio', 'Administrator', 'LEMON GEM CUPCAKES', '', '"What a delicious lemon cupcake! It''s light, delicate and not too sweet! I used a bit of lemon extract to enhance the flavor."', 'October 10, 2016 04:50 PM', 'DESIGN2', '1 1?3 cups| all-purpose flour|\r\n1?2 teaspoon| baking powder|\r\n3?4 teaspoon| baking soda|\r\n1?4 teaspoon| salt|\r\n1?4 cup| canola oil|\r\n2?3 cup| sugar, plus|\r\n2 tablespoons| sugar|\r\n1 cup| rice milk|\r\n1 teaspoon| vanilla extract|\r\n1?4 cup| lemon juice|\r\n1 tablespoon| lemon zest|\r\n1?4 cup| vegan margarine, softened (non hydrogenated)|\r\n1?4 cup| soymilk|\r\n2 tablespoons| lemon juice|\r\n2 cups| confectioners'' sugar, sifted| \r\n', 'FREE', ''),
(26, 'Mae Gregorio', 'Administrator', 'PEANUT BUTTER TRUFFLE CUPCAKES', '', '"I can''t say enough about these wonderful chocolate cupcakes — they''re a must-try for any peanut butter and chocolate lover! To save time, I made the truffles a day ahead."', 'October 10, 2016 04:51 PM', 'DESIGN2', '6 ounces| squares white baking chocolate, coarsely chopped|\r\n1?4 cup| creamy peanut butter|\r\n2 tablespoons |baking cocoa|\r\n1?2 cup| butter, softened|\r\n3?4 cup| sugar|\r\n2| eggs|\r\n1 teaspoon| vanilla|\r\n3?4 cup| flour|\r\n1?2 cup| baking cocoa|\r\n1?2 teaspoon| baking soda|\r\n1?4 teaspoon| salt|\r\n1?2 cup| buttermilk|\r\n1?2 cup| strong brewed coffee|\r\n3 ounces| squares semisweet chocolate, chopped|\r\n1?3 cup| heavy whipping cream|\r\n3 tablespoons| creamy peanut butter| \r\n', 'FREE', ''),
(27, 'Mae Gregorio', 'Administrator', 'TIRAMISU CUPCAKES', '', '"I give these 10 stars! They are absolutely wonderful and very easy. The mascarpone filling is to die for. I had to restrain myself from eating all of it before I used it in the recipe!"', 'October 10, 2016 04:52 PM', 'DESIGN2', '1 (18 1/4 ounce)| package white cake mix|\r\n3| eggs|\r\n1?3 cup| oil|\r\n1 1?4| cups water|\r\n2?3 cup| water, boiling|\r\n1?2 cup| confectioners'' sugar|\r\n1 1?2 tablespoons| instant coffee|\r\nMascarpone Filling\r\n\r\n1 cup| mascarpone cheese (from tub)|\r\n3 tablespoons| Kahlua (or coffee extract)|\r\n1?4 cup| sweetened condensed milk|\r\n1 (8 ounce)| container french vanilla cool whip|\r\n1 (8 ounce)| package cream cheese, softened|\r\n1?2 cup| butter, softened|\r\n2 cups| confectioners'' sugar|\r\n1 teaspoon| vanilla extract|\r\n1pc| chocolate shavings (to garnish)| \r\n', 'FREE', ''),
(28, 'Mae Gregorio', 'Administrator', 'RED VELVET CUPCAKES', '', '"This has been my go-to recipe for at least three years. My friends and family demand it for every party. Don''t skimp on the food coloring — it seems way too red, but it comes out perfectly and everyone loves it."', 'October 10, 2016 04:53 PM', 'DESIGN2', '1 (18 1/4 ounce) package| yellow cake mix|\r\n2 tablespoons| unsweetened baking cocoa|\r\n5| large eggs|\r\n1?2 cup| vegetable oil|\r\n1 cup| buttermilk|\r\n2 (1 ounce) bottles| red food coloring (do not reduce amount!)|\r\n1pc| cream cheese frosting| \r\n', 'FREE', ''),
(29, 'Mae Gregorio', 'Administrator', 'OREO CUPCAKES WITH OREO BUTTERCREAM', '', 'Oreo fans take note: This is your go-to cupcake from now on. With a creamy cookie-based batter, frosting and topping, it''s Oreo heaven!', 'October 10, 2016 04:54 PM', 'DESIGN2', '3 cups| cake flour|\r\n1 tablespoon| baking powder|\r\n1?2 teaspoon| salt|\r\n16 tablespoons| unsalted butter, at room temperature|\r\n2 cups| sugar|\r\n5| large eggs, at room temperature|\r\n1 1?4 cups| buttermilk, at room temperature|\r\n1 tablespoon| vanilla extract|\r\n20| Oreo cookies (halves, with cream filling attached)|\r\n8 tablespoons| butter, room temperature|\r\n1?2 cup| vegetable shortening|\r\n4 cups| powdered sugar (1 lb)|\r\n1?2 teaspoon| butter flavoring or 1?2 teaspoon vanilla extract|\r\n6 tablespoons| Oreo cookies, finely crushed|\r\n10| Oreo cookies, cut in half, for garnish| \r\n', 'FREE', ''),
(30, 'Mae Gregorio', 'Administrator', 'TROPICAL SPICE CUPCAKES', '', '"Excellent! I loved the cupcakes'' flavor — orange with a hint of coconut. They were even better the day after I baked them!"', 'October 10, 2016 04:55 PM', 'DESIGN2', '2 1?2 cups| cake flour|\r\n1 teaspoon| baking powder|\r\n1 teaspoon| baking soda|\r\n1 teaspoon| salt|\r\n1 teaspoon| cinnamon|\r\n1?2 teaspoon| ground ginger|\r\n1?4 teaspoon| ground nutmeg|\r\n1?4 teaspoon| ground cloves|\r\n1?2 cup| butter, room temperature|\r\n1?2 cup| brown sugar|\r\n1 cup| sugar|\r\n2| eggs|\r\n1 teaspoon| Grand Marnier|\r\n1| large orange, juice and zest of, for use in the recipe|\r\n1?2 cup| coconut milk|\r\n1?2 cup| buttermilk|\r\n1?2 cup |coconut|\r\n2 tablespoons| orange juice, from the freshly juiced oranges|\r\n2 tablespoons| coconut milk|\r\n1?2 teaspoon| Grand Marnier|\r\n2 ounces| cream cheese, room temperature|\r\n3 1?2-4 cups| confectioners'' sugar| \r\n', 'FREE', ''),
(31, 'Mae Gregorio', 'Administrator', 'STRABUCKS COPYCAT CUPCAKES', '', '"Awesome! Everyone loved these and couldn''t get enough. For the second batch, I added mini chocolate chips and dark cocoa instead of regular and it was incredible."', 'October 10, 2016 04:56 PM', 'DESIGN2', '2 cups| flour|\r\n2 cups| sugar|\r\n3?4 cup| cocoa powder|\r\n2 teaspoons| baking soda|\r\n1 teaspoon| baking powder|\r\n1 teaspoon| salt|\r\n2| large eggs|\r\n1?2 cup| canola oil|\r\n1 cup| milk|\r\n1 teaspoon| vanilla|\r\n8 ounces| starbucks black coffee, cooled (or any brand can be substituted)| \r\n', 'FREE', ''),
(32, 'Mae Gregorio', 'Administrator', 'SIMPLE VANILLA CUPCAKES', '', 'These vanilla cupcakes are so tasty and easy to make. Plus, they make an excellent canvas for your favorite icing!', 'October 10, 2016 04:56 PM', 'DESIGN2', '2 cups| flour|\r\n1?2 teaspoon| salt|\r\n2 teaspoons| baking powder|\r\n1?2 cup| butter, softened|\r\n3?4 cup| sugar (if you like your cupcakes very sweet, add a little more.)|\r\n2| eggs|\r\n1 cup| milk|\r\n1 teaspoon| vanilla essence (optional)|\r\n', 'FREE', ''),
(33, 'Mae Gregorio', 'Administrator', 'FROG CUPCAKES', '', '"Brilliant! I made these cupcakes for the kids'' table at our annual family picnic, and they were a huge hit with the kids as well as the adults."', 'October 10, 2016 04:57 PM', 'DESIGN2', '24| cupcakes, cooked and prepared for frosting|\r\n2 cups| green frosting|\r\n24| gumdrops, green|\r\n48| white chocolate chips|\r\n1pc| black decorating gel|\r\n', 'FREE', ''),
(34, 'Mae Gregroio', 'Administrator', 'PECAN PIE CUPCAKES', '', '"Awesome little cupcake — no one could eat just one! To prevent them from sticking to the pan, flip them out as soon as they come out of the oven."', 'October 10, 2016 04:58 PM', 'DESIGN2', '1 cup| chopped pecans|\r\n1?2 cup| all-purpose flour|\r\n1 cup| packed brown sugar|\r\n2?3 cup| butter, melted|\r\n2| eggs|\r\n', 'FREE', ''),
(35, 'Mae Gregorio', 'Administrator', 'BLACK BOTTOM CUPCAKES', '', '"It''s a good thing there were other people in the house when I made these cupcakes, because I''d have eaten them all by myself! I LOVE how moist they are! I made some with and without the almonds, and they were great both ways."', 'October 10, 2016 04:59 PM', 'DESIGN2', '2 cups| flour|\r\n1 cup| sugar|\r\n1?4 cup| cocoa|\r\n1 teaspoon| baking soda|\r\n1?2 teaspoon| salt|\r\n1 cup| water, plus|\r\n2 tablespoons| water|\r\n1?3 cup| oil, plus|\r\n1 tablespoon| oil|\r\n1 tablespoon| vinegar|\r\n1 teaspoon| vanilla|\r\n1 cup| chocolate chips|\r\n1 (8 ounce) package| cream cheese, softened|\r\n1?3 cup| powdered sugar|\r\n1pc| slivered almonds, if desired|\r\n', 'FREE', ''),
(36, 'Mae Gregroio', 'Administrator', 'CHURRO CUPCAKES', '', '"These were very easy to make and they tasted fantastic."', 'October 10, 2016 05:00 PM', 'DESIGN2', '1 1?2 cups| all-purpose flour|\r\n1 1?2 teaspoons| cinnamon|\r\n1 1?2 teaspoons| baking powder|\r\n1?2 teaspoon| salt|\r\n1?2 cup| unsalted butter, at room temperature (1 stick)|\r\n1 cup| sugar|\r\n2| eggs|\r\n2 teaspoons| vanilla extract|\r\n1?4 cup| vegetable oil|\r\n1?2 cup| milk|\r\n4 ounces| cream cheese, at room temperature|\r\n4 tablespoons| unsalted butter, at room temperature|\r\n2 cups| confectioners'' sugar|\r\n1 teaspoon| vanilla extract|\r\n1 teaspoon| cinnamon|\r\n', 'FREE', ''),
(37, 'Mae Gregorio', 'Administrator', 'SPECIAL MOCHA CUPCAKES', '', '"Topped with a fluffy frosting and chocolate sprinkles, these extra rich, extra delicious cupcakes smell wonderful while baking — and taste even better!"', 'October 10, 2016 05:01 PM', 'DESIGN2', '1 1?2 cups| flour|\r\n1 cup| sugar|\r\n1?3 cup| baking cocoa|\r\n1 teaspoon| baking soda|\r\n1?2 teaspoon| salt|\r\n2| eggs|\r\n1?2 cup| cold brewed coffee|\r\n1?2 cup| vegetable oil|\r\n3 teaspoons| cider vinegar|\r\n3 teaspoons| vanilla extract|\r\n3 tablespoons| semi-sweet chocolate chips|\r\n3 tablespoons| milk chocolate chips|\r\n1?3 cup| butter, softened|\r\n2 cups| confectioners'' sugar|\r\n1 -2 tablespoon| brewed coffee|\r\n1?2 cup| chocolate sprinkles|\r\n', 'FREE', ''),
(38, 'Mae Gregroio', 'Administrator', 'RAINBOW BRIGHT CUPCAKES', '', 'Kids and adults alike will love these festive rainbow cupcakes! Their secret ingredient (sour cream — shhh!) makes them extra rich.', 'October 10, 2016 05:02 PM', 'DESIGN2', '1 (18 ounce) box| yellow cake mix|\r\n4| eggs|\r\n1?2 cup| vegetable oil|\r\n1?2 cup| water|\r\n8 ounces| sour cream|\r\n1 small| vanilla instant pudding mix|\r\n1pc| food coloring (Red, Blue, Yellow, Green and Purple)|\r\n1pc| vanilla or cream cheese frosting, of choice|\r\n', 'FREE', ''),
(39, 'Mae Gregroio', 'Administrator', 'LEMON GEMS CUPCAKES', '', '"What a delicious lemon cupcake! It''s light, delicate and not too sweet! I used a bit of lemon extract to enhance the flavor."', 'October 10, 2016 05:03 PM', 'DESIGN2', '1 1?3 cups| all-purpose flour|\r\n1?2 teaspoon| baking powder|\r\n3?4 teaspoon| baking soda|\r\n1?4 teaspoon| salt|\r\n1?4 cup| canola oil|\r\n2?3 cup| sugar, plus|\r\n2 tablespoons| sugar|\r\n1 cup| rice milk|\r\n1 teaspoon| vanilla extract|\r\n1?4 cup| lemon juice|\r\n1 tablespoon| lemon zest|\r\n1?4 cup| vegan margarine, softened (non hydrogenated)|\r\n1?4 cup| soymilk|\r\n2 tablespoons| lemon juice|\r\n2 cups| confectioners'' sugar, sifted|\r\n', 'FREE', ''),
(40, 'Mae Gregorio', 'Administrator', 'BANANA WALNUT CUPCAKES WITH CREAM CHEESE FROSTING', '', '"These cupcakes are wonderful. They were a hit! They were great the first day and even the second day. I will definitely be making these cupcakes a lot."', 'October 10, 2016 05:04 PM', 'DESIGN2', '1 cup| flour|\r\n2| bananas (mashed)|\r\n1?2 teaspoon| baking soda|\r\n1?4 teaspoon| salt|\r\n1 teaspoon| vanilla|\r\n1?2 cup| granulated sugar|\r\n3?4 cup| brown sugar|\r\n2| eggs|\r\n1?2 cup| butter|\r\n3?4 cup| walnuts (in small pieces)|\r\n1?4 cup| vanilla yogurt|\r\n4 ounces| cream cheese|\r\n1 teaspoon| vanilla|\r\n1 3?4 cups| confectioners'' sugar|\r\n', 'FREE', ''),
(41, 'Mae Gregorio', 'Administrator', 'PINK LEMONADE CUPCAKES', '', '"These cupcakes are so moist, not to mention that they have the perfect balance of sweet and tangy! I took them to a ladies'' tea and they were a big hit."', 'October 10, 2016 05:05 PM', 'DESIGN2', '1 cup| all-purpose flour|\r\n1?2 teaspoon| baking powder|\r\n1?4 teaspoon| baking soda|\r\n1 pinch| salt|\r\n1?2 cup| granulated sugar|\r\n1?4 cup| canola oil|\r\n2| egg whites|\r\n1?3 cup| frozen pink lemonade concentrate, thawed|\r\n1?4 cup| buttermilk|\r\n3 drops| red food coloring|\r\n1 1?2 cups| icing sugar, sifted to remove lumps (or more as needed)|\r\n1?2 cup| unsalted butter, room temp|\r\n1 pinch| salt|\r\n1?4 cup| whipping cream|\r\n2 teaspoons| frozen pink lemonade concentrate, thawed|\r\n1 teaspoon| lemon extract|\r\n3 drops| red food coloring|\r\n', 'FREE', ''),
(42, 'Mae Gregorio', 'Administrator', 'ONE-BOWL CHOCOLATE CUPCAKES', '', '"This is so easy to make! It receives great reviews from my family, who said it''s fluffy and moist, but not too rich."', 'October 10, 2016 05:06 PM', 'DESIGN2', '3?4 cup| unsweetened cocoa powder|\r\n1 1?2 cups| all-purpose flour|\r\n1 1?2 cups |sugar|\r\n1 1?2 teaspoons| baking soda|\r\n3?4 teaspoon| baking powder|\r\n3?4 teaspoon| salt|\r\n2| large eggs|\r\n3?4 cup| warm water|\r\n3?4 cup| buttermilk|\r\n3 tablespoons| safflower oil|\r\n1 teaspoon| pure vanilla extract|\r\n', 'FREE', ''),
(43, 'Mae Gregorio', 'Administrator', 'PUMPKIN CUPCAKES', '', '"Unbelievable! So smooth, soft and light! For extra flavor, I increased the spice to 2 teaspoons."', 'October 10, 2016 05:07 PM', 'DESIGN2', '2 cups| flour|\r\n1 cup| white sugar|\r\n1 1?2 teaspoons| baking powder|\r\n1 teaspoon| baking soda|\r\n1 1?2 teaspoons| pumpkin pie spice|\r\n1?2 teaspoon| salt|\r\n2| eggs|\r\n1 cup| pumpkin puree|\r\n1?2 cup| buttermilk|\r\n1?4 cup| vegetable oil|\r\n250 g| cream cheese, softened|\r\n1 tablespoon| butter|\r\n1 teaspoon| vanilla|\r\n1 cup| icing sugar|\r\n1pc| orange sprinkles (optional)|\r\n', 'FREE', ''),
(44, 'Mae Gregorio', 'Administrator', 'LAVENDER CUPCAKES', '', '"This is such a special and attractive recipe. They were so easy and looked so elegant on the serving table. Everyone at our party — men, women AND picky kids — loved them."', 'October 10, 2016 05:07 PM', 'DESIGN2', '1?2 cup| granulated sugar|\r\n1?4 teaspoon| dried lavender flowers|\r\n1?2 cup| butter, at room temperature|\r\n2| eggs|\r\n1 cup| self-rising flour|\r\n2 tablespoons| milk|\r\n1 1?2 cups| confectioners'' sugar, sifted|\r\n1| egg white|\r\n1PC| lilac food coloring|\r\n12| sprigs of fresh lavender (optional)|\r\n', 'FREE', ''),
(45, 'Mae Gregorio', 'Administrator', 'CHOCOLATE CUPCAKES WITH NUTELLA -KAHLUA GANACHE AND FERERO ROCHER', '', '"So chocolatey and decadent! The Nutella-Kahlua ganache is so tasty that you will find yourself trying not to eat it all before you top the cupcakes."', 'October 10, 2016 05:08 PM', 'DESIGN2', '1 cup| all-purpose flour|\r\n1?4 cup| unsweetened cocoa powder|\r\n1?2 teaspoon| salt|\r\n1?2 teaspoon| baking soda|\r\n1 teaspoon| orange zest|\r\n1?2 cup| butter, room temperature|\r\n1 cup| sugar|\r\n2| large eggs|\r\n1?2 cup| sour cream|\r\n1?4 cup| warm milk|\r\n2 teaspoons| pure vanilla extract|\r\n12| ferrero rocher candies, roughly chopped|\r\n1?2 cup| heavy cream|\r\n6 ounces| nutella (4 oz if whipped ganache is desired)|\r\n1 teaspoon| Kahlua|\r\n1?8 teaspoon| salt|\r\n', 'FREE', ''),
(46, 'Mae Gregorio', 'Administrator', 'PINEAPPLE UPSIDE-DOWN CUPCAKES', '', '"Oh wow! These are fabulous! They''re very moist and full of flavor thanks to the pineapple juice."', 'October 10, 2016 05:09 PM', 'DESIGN2', '1 duncan| hines pineapple supreme cake mix|\r\n1pc| oil, and eggs called for on cake mix box|\r\n1pc| pineapple juice, in place of water called for on box (you don''t have to use pineapple juice, I just think it enhances the flavor!)|\r\n1 (20 ounce)| can pineapple tidbits (save the juice!)|\r\n1 1?2 cups| light brown sugar|\r\n1?2 cup| butter, melted|\r\n24| maraschino cherries|\r\n', 'FREE', ''),
(47, 'Mae Gregorio', 'Administrator', 'CHOCOLATE CUPCAKES WITH CHEESECAKE CENTER', '', '"These are unbelievably wonderful, brownie-like cupcakes! I had to grab three for a photo before everybody stole them!"', 'October 10, 2016 05:10 PM', 'DESIGN2', '3 cups| all-purpose flour|\r\n2 1?3 cups| sugar, divided|\r\n2?3 cup| unsweetened cocoa powder|\r\n2 teaspoons| baking soda|\r\n1 1?8 teaspoons| salt, divided|\r\n2 cups| water|\r\n2?3 cup| vegetable oil|\r\n2 tablespoons| white vinegar|\r\n2 teaspoons| vanilla extract|\r\n8 ounces| cream cheese, softened|\r\n1| egg|\r\n', 'FREE', ''),
(48, 'Mae Gregorio', 'Administrator', 'STRAWBERRY AND CREAM CUPCAKES', '', '"Loved these cupcakes! The strawberry soda really gives them a sweet, fruity flavor, and they''re so moist!"', 'October 10, 2016 05:11 PM', 'DESIGN2', '1 (18 1/4 ounce) box| white cake mix (calls for Betty Crocker Supermoist)|\r\n1 1?4 cups| strawberry soda|\r\n1?3 cup| vegetable oil|\r\n3| egg whites|\r\n1pc| red food coloring|\r\n1 (16 ounce)| can cream cheese frosting|\r\n1?2 cup| white candy sprinkles|\r\n1pc| fresh strawberries, if desired|\r\n', 'FREE', ''),
(49, 'Mae Gregorio', 'Administrator', 'BAREFOOT CONTESSA’S CARROT CAKE CUPCAKES', '', '"Gotta love my girl Ina! I baked the cupcakes at 400 degrees F for 10 minutes, and then for 15 minutes at 350 degrees F. They were very moist and delicious!"', 'October 10, 2016 05:12 PM', 'DESIGN2', '2 cups| sugar|\r\n1 1?3 cups| vegetable oil|\r\n1 teaspoon| pure vanilla extract|\r\n3| extra-large eggs|\r\n2 cup|s all-purpose flour|\r\n2 teaspoons| ground cinnamon|\r\n2 teaspoons| baking soda|\r\n1 1?2 teaspoons| kosher salt|\r\n3 cups| grated carrots (less than 1 pound)|\r\n1 cup| raisins|\r\n1 cup| chopped walnuts|\r\n3?4 lb| cream cheese, at room temperature|\r\n1?2 lb| unsalted butter, at room temperature|\r\n1 teaspoon| pure vanilla extract|\r\n1 lb| confectioners'' sugar|\r\n', 'FREE', ''),
(50, 'Mae Gregorio', 'Administrator', 'CHERRY CHEESECAKE CUPCAKES', '', '"Amazing! I made these for my boyfriend''s work function and he came back with rave reviews. The recipe can easily be doubled, and next time I''ll have to do that since people ate them like crazy! It''s an awesome recipe."', 'October 10, 2016 05:13 PM', 'DESIGN2', '28| cupcake liners|\r\n1 (8 ounce) package| cream cheese, at room temperature|\r\n1?3 cup| sugar|\r\n|1 large egg|\r\n1?2 teaspoon| vanilla|\r\n1 (18 1/4 ounce) package| yellow cake mix|\r\n1 (3 1/2 ounce) package| vanilla instant pudding mix|\r\n1 cup| whole milk|\r\n2?3 cup| vegetable oil|\r\n3| large eggs|\r\n1 teaspoon| almond extract|\r\n28| vanilla wafers|\r\n1 (21 ounce)| can cherry pie filling|\r\n1?4 cup| powdered sugar|\r\n', 'FREE', ''),
(51, 'Mae Gregorio', 'Administrator', 'ZUCCHINI CUPCAKES', '', '"These cupcakes are so scrumptious! The icing is to die for. My hubby had to pull the pan out of my hands after I was done frosting them."', 'October 10, 2016 05:14 PM', 'DESIGN2', '3| eggs|\r\n1 1?3 cups| sugar|\r\n1?2 cup| vegetable oil|\r\n1?2 cup| orange juice|\r\n1 teaspoon| almond extract|\r\n2 1?2 cups| all-purpose flour|\r\n2 teaspoons| ground cinnamon|\r\n2 teaspoons| baking powder|\r\n1 teaspoon| baking soda|\r\n1 teaspoon| salt|\r\n1?2 teaspoon| ground cloves|\r\n1 1?2 cups| shredded zucchini|\r\n1 cup| packed brown sugar|\r\n1?2 cup| butter or 1?2 cup margarine|\r\n1?4 cup| milk|\r\n1 teaspoon| vanilla extract|\r\n1 1?2-2 cups| confectioners'' sugar|\r\n', 'FREE', ''),
(52, 'Mae Gregorio', 'Administrator', 'PEPPERMINT CUPCAKES', '', '"We loved these! All I could find to use in place of candy canes were Altoids mints crushed finely in my food processor. It worked well; it made the cupcakes and frosting very minty and refreshing!"', 'October 10, 2016 05:15 PM', 'DESIGN2', '12| candy canes|\r\n1 (18 1/4 ounce) box| of duncan hines moist deluxe devil''s food cake mix|\r\n1 1?3 cups| water|\r\n1?2 cup| vegetable oil|\r\n3| large eggs|\r\n1?4 teaspoon| peppermint extract|\r\n16 ounces| vanilla frosting|\r\n', 'FREE', ''),
(53, 'Mae Gregorio', 'Administrator', 'MARMALADE CUPCAKES', '', '"This is pretty much the perfect cupcake: buttery, moist and not too sweet, with little flecks of orange rind. Delicious!"', 'October 10, 2016 05:29 PM', 'DESIGN2', '2 cups| all-purpose flour|\r\n1?2 teaspoon| baking powder|\r\n1?2 teaspoon| baking soda|\r\n1?4 teaspoon| salt|\r\n1?2 cup| butter or 1?2 cup margarine, softened|\r\n1 cup| granulated sugar|\r\n3| large eggs|\r\n1 cup| orange marmalade|\r\n1?2 cup| buttermilk|\r\n', 'FREE', ''),
(54, 'Mae Gregorio', 'Administrator', 'DOUBLE CHOCOLATE AND ORANGE CUPCAKES', '', 'Orange is the star ingredient in these cupcakes — its bright citrus flavor provides the perfect balance to the slimmed-down chocolatey batter!', 'October 10, 2016 05:30 PM', 'DESIGN2', '1 1?2 cups| flour|\r\n1?2 cup| sugar|\r\n1?4 cup| cocoa|\r\n1 teaspoon| baking soda|\r\n1?2 teaspoon| salt|\r\n1?2 cup| orange juice|\r\n3 tablespoons| oil|\r\n1 tablespoon| vinegar|\r\n1 teaspoon| vanilla|\r\n1?3 cup| water|\r\n1?3 cup| mini chocolate chip|\r\n1 teaspoon| confectioners'' sugar (optional)|\r\n', 'FREE', ''),
(55, 'Mae Gregorio', 'Administrator', 'MINI DOUGHNUT CUPCAKES', '', '"The taste and texture is just like a doughnut! Tip: The batter is super thick, so it has to be spooned and then pushed with a spatula into the baking cups."', 'October 10, 2016 05:31 PM', 'DESIGN2', '1 cup| sugar|\r\n1 1?2 teaspoons| ground cinnamon|\r\n1 (18 1/4 ounce) package| yellow cake mix|\r\n1?8 cup| water|\r\n1?2 cup| vegetable oil|\r\n3| eggs|\r\n1 tablespoon| ground nutmeg|\r\n', 'FREE', '');

-- --------------------------------------------------------

--
-- Table structure for table `services`
--

CREATE TABLE `services` (
  `NO` int(11) NOT NULL,
  `CLIENT` varchar(100) NOT NULL,
  `DATE` varchar(100) NOT NULL,
  `INFO` varchar(1000) NOT NULL,
  `DESCRIPTION` varchar(5000) NOT NULL,
  `FORMAT` varchar(100) NOT NULL,
  `IMAGEVIDEOURL` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `services`
--

INSERT INTO `services` (`NO`, `CLIENT`, `DATE`, `INFO`, `DESCRIPTION`, `FORMAT`, `IMAGEVIDEOURL`) VALUES
(1, 'Lorem ipsum', 'July 07, 2012 04:06 PM', 'Phasellus ultrices tellus eget ipsum', 'This format perfectly fits in case you need only a single image for your post display. Use Featured image option to add image to the post.|Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In faucibus, risus eu volutpat pellentesque, massa felis feugiat velit, nec mattis felis elit a eros.|Cras convallis sodales orci, et pretium sapien egestas quis. Donec tellus leo, scelerisque in facilisis a, laoreet vel quam. Suspendisse arcu nisl, tincidunt a vulputate ac, feugiat vitae leo. Integer hendrerit orci id metus venenatis in luctus.', 'IMAGE FORMAT', 's1.jpg'),
(2, 'Lorem ipsum', 'July 07, 2012 05:10 PM', 'Phasellus ultrices tellus', 'This format can be used to display images as a slideshow. To attach images to the post please use Upload Images button.|Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In faucibus, risus eu volutpat pellentesque, massa felis feugiat velit, nec mattis felis elit a eros.|Cras convallis sodales orci, et pretium sapien egestas quis. Donec tellus leo, scelerisque in facilisis a, laoreet vel quam. Suspendisse arcu nisl, tincidunt a vulputate ac, feugiat vitae leo. Integer hendrerit orci id metus venenatis in luctus.', 'SLIDESHOW FORMAT', 's2.jpg'),
(3, 'Lorem ipsum', 'August 12, 2013', 'Phasellus ultrices tellus eget ipsum', 'If your post contains video, please use this format. Select Video format in the appeared metabox and add the embed code from the video hosting you use (youtube, vimeo etc)|Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In faucibus, risus eu volutpat pellentesque, massa felis feugiat velit, nec mattis felis elit a eros.|Cras convallis sodales orci, et pretium sapien egestas quis. Donec tellus leo, scelerisque in facilisis a, laoreet vel quam. Suspendisse arcu nisl, tincidunt a vulputate ac, feugiat vitae leo. Integer hendrerit orci id metus venenatis in luctus.', 'VIDEO FORMAT', 's3.m4v');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `USER_ID` int(11) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  `PHONENUMBER` varchar(11) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `ACCOUNT_TYPE` varchar(50) NOT NULL,
  `REG_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTIVATED` tinyint(4) NOT NULL,
  `TEMPLATENAME` varchar(50) NOT NULL,
  `VERIFIED` varchar(50) NOT NULL,
  `VERIFICATIONCODE` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`USER_ID`, `NAME`, `USERNAME`, `PHONENUMBER`, `EMAIL`, `PASSWORD`, `ACCOUNT_TYPE`, `REG_TIME`, `ACTIVATED`, `TEMPLATENAME`, `VERIFIED`, `VERIFICATIONCODE`) VALUES
(1, 'John Mark C. Abril', '', '', 'johnmarkabril@gmail.com', '34c87211821751f911c058bbf0cfb822', 'Administrator', '2016-07-31 06:13:37', 0, 'MAIN', '', ''),
(2, 'Farrah Mae Gregorio', '', '', 'frrhmgrgrio@gmail.com', '19a2be974580740e9ec96ab7fc016d1b', 'User', '2016-07-31 11:59:26', 0, 'MAIN', '', ''),
(3, 'Jm Abril', 'jmabril17', '09208317004', 'johnmark_abri12l@yahoo.com', '89daf6d74eeceabf2e74efe50f41c9b2', 'User', '2016-09-21 19:25:23', 0, 'DESIGN2', 'YES', ''),
(4, 'Mae Gregorio', 'gregs17', '09306625692', 'maegregorio@gmail.com', '7950b6bd370f715554900616819ffc4e', 'Administrator', '2016-09-21 19:43:18', 0, 'DESIGN2', 'NO', ''),
(17, 'John Doe', 'johndoe123', '09123654987', 'johndoe@example.com', 'd1b2cc725d846f0460ff290c60925070', 'User', '0000-00-00 00:00:00', 0, 'DESIGN2', 'NO', 'Vne0q04A');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `comment_section_post`
--
ALTER TABLE `comment_section_post`
  ADD PRIMARY KEY (`NO`);

--
-- Indexes for table `posted`
--
ALTER TABLE `posted`
  ADD PRIMARY KEY (`NO`);

--
-- Indexes for table `services`
--
ALTER TABLE `services`
  ADD PRIMARY KEY (`NO`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`USER_ID`),
  ADD UNIQUE KEY `EMAIL` (`EMAIL`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `comment_section_post`
--
ALTER TABLE `comment_section_post`
  MODIFY `NO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
--
-- AUTO_INCREMENT for table `posted`
--
ALTER TABLE `posted`
  MODIFY `NO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;
--
-- AUTO_INCREMENT for table `services`
--
ALTER TABLE `services`
  MODIFY `NO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `USER_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
